create table if not exists public.products (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null default '',
  price numeric(10, 2) not null check (price >= 0),
  image_url text not null,
  is_available boolean not null default true
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  customer_name text not null,
  phone_number text not null,
  address text not null,
  cart_items jsonb not null,
  total_price numeric(10, 2) not null check (total_price >= 0),
  payment_method text not null default 'Cash on Delivery',
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  email text unique not null,
  password_hash text not null,
  created_at timestamptz not null default now()
);

create extension if not exists pgcrypto with schema extensions;

create or replace function public.verify_admin_password(login_email text, login_password text)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users
    where email = lower(trim(login_email))
      and password_hash = extensions.crypt(login_password, password_hash)
  );
$$;

revoke all on function public.verify_admin_password(text, text) from public, anon, authenticated;
grant execute on function public.verify_admin_password(text, text) to service_role;

alter table public.admin_users enable row level security;

insert into public.admin_users (email, password_hash)
values ('nahidhasan.workpost@gmail.com', extensions.crypt('NookAdmin123!', extensions.gen_salt('bf')))
on conflict (email) do nothing;

alter table public.products enable row level security;
alter table public.orders enable row level security;

create policy "Anyone can read available products"
  on public.products for select
  using (is_available = true);

create policy "Anyone can create orders"
  on public.orders for insert
  with check (true);

insert into public.products (title, description, price, image_url)
values
  ('Morning Ritual Set', 'A calm three-piece reset for your everyday start.', 1290, 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=900&q=85'),
  ('Linen Carryall', 'Roomy, structured and ready for the everyday commute.', 890, 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=900&q=85'),
  ('Soft Form Candle', 'Warm cedar, amber and a slow evening in one small vessel.', 690, 'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=900&q=85'),
  ('Desk Reset Kit', 'Small tools for a cleaner desk and a clearer head.', 1590, 'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=900&q=85')
on conflict do nothing;
